spring:
  application:
    name: agriconnect-capteur
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/agriconnect-capteurs?serverTimezone=UTC
    username: root
    password: root

server:
  port: 8081

springdoc:
  api-docs:
    path: /api/swagger

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

